# 
# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
# 
a = [1,2]
next_num = 0
sum = 2
while next_num < 4000000 do
  p next_num
  next_num = a[0] + a[1]
  sum += next_num if next_num % 2 == 0
  a[0] = a[1]
  a[1] = next_num
end
p sum
